# Generated by Django 5.2.14 on 2026-05-31 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('normalized_topic', models.CharField(db_index=True, max_length=500)),
                ('source', models.CharField(choices=[('GOOGLE_TRENDS_KE', 'Google Trends Kenya'), ('TWITTER_TRENDING_KE', 'X trends Kenya'), ('NEWS_KE', 'Kenyan news'), ('OPERATOR_MANUAL', 'Operator manual')], max_length=32)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('popularity_score', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('fetched_at', models.DateTimeField(db_index=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'constraints': [models.UniqueConstraint(fields=('normalized_topic', 'source', 'fetched_at'), name='uniq_trend_signal_per_source_time')],
            },
        ),
        migrations.CreateModel(
            name='AITrendSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_topic', models.CharField(max_length=500)),
                ('trend_source', models.CharField(choices=[('GOOGLE_TRENDS_KE', 'Google Trends Kenya'), ('TWITTER_TRENDING_KE', 'X trends Kenya'), ('NEWS_KE', 'Kenyan news'), ('OPERATOR_MANUAL', 'Operator manual')], max_length=32)),
                ('suggestion_type', models.CharField(choices=[('TREND_BASED', 'Trend based'), ('EVERGREEN', 'Evergreen'), ('CAMPAIGN_IDEA', 'Campaign idea'), ('CAPTION_VARIANT', 'Caption variant'), ('HASHTAG_SET', 'Hashtag set')], max_length=32)),
                ('suggested_caption', models.TextField(blank=True)),
                ('suggested_hashtags', models.JSONField(blank=True, default=list)),
                ('suggested_platforms', models.JSONField(blank=True, default=list)),
                ('rationale', models.TextField(blank=True)),
                ('content_angle', models.TextField(blank=True)),
                ('relevance_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('fetched_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='clients.client')),
                ('trend_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='ai_studio.trendsignal')),
            ],
            options={
                'ordering': ['-fetched_at', '-relevance_score'],
                'indexes': [models.Index(fields=['client', 'expires_at'], name='ai_studio_a_client__22320b_idx')],
            },
        ),
    ]
