# Generated by Django 5.2.14 on 2026-05-31 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('clients', '0001_initial'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], default='UPLOADED', max_length=16)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_imports', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_imports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('QUEUED', 'Queued'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('first_comment_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='campaigns.campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to=settings.AUTH_USER_MODEL)),
                ('is_clone_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='publishing.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('STATUS_CHANGED', 'Status changed'), ('RESCHEDULED', 'Rescheduled'), ('RETRIED', 'Retried')], max_length=32)),
                ('previous_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('QUEUED', 'Queued'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], max_length=16)),
                ('new_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('QUEUED', 'Queued'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], max_length=16)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='publishing.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='#64748b', max_length=7)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_labels', to='clients.client')),
            ],
            options={
                'ordering': ['client', 'name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='posts', to='publishing.postlabel'),
        ),
        migrations.CreateModel(
            name='PostQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_slots', to='clients.client')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_slots', to='integrations.socialaccount')),
            ],
            options={
                'ordering': ['client', 'social_account', 'day_of_week', 'time'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='queue_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='publishing.postqueue'),
        ),
        migrations.CreateModel(
            name='PostTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('GBP', 'Google Business Profile'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('LINKEDIN', 'LinkedIn'), ('TWITTER', 'X / Twitter')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHING', 'Publishing'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('platform_post_id', models.CharField(blank=True, max_length=255)),
                ('platform_url', models.URLField(blank=True, max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('first_comment_status', models.CharField(choices=[('NOT_REQUESTED', 'Not requested'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='NOT_REQUESTED', max_length=16)),
                ('first_comment_error', models.TextField(blank=True)),
                ('first_comment_platform_id', models.CharField(blank=True, max_length=255)),
                ('first_comment_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='publishing.post')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_targets', to='integrations.socialaccount')),
            ],
            options={
                'ordering': ['post', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='PostPlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('post_target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_config', to='publishing.posttarget')),
            ],
        ),
        migrations.CreateModel(
            name='PostTargetMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_json', models.JSONField(default=dict)),
                ('collected_at', models.DateTimeField(db_index=True)),
                ('post_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='publishing.posttarget')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('data_json', models.JSONField(default=dict)),
                ('errors_json', models.JSONField(blank=True, default=list)),
                ('bulk_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='publishing.bulkimport')),
                ('imported_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_import_rows', to='publishing.post')),
            ],
            options={
                'ordering': ['bulk_import', 'row_number'],
                'constraints': [models.UniqueConstraint(fields=('bulk_import', 'row_number'), name='uniq_bulk_import_row_number')],
            },
        ),
        migrations.AddConstraint(
            model_name='postlabel',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='uniq_post_label_per_client'),
        ),
        migrations.AddConstraint(
            model_name='postqueue',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='queue_day_of_week_between_0_and_6'),
        ),
        migrations.AddConstraint(
            model_name='postqueue',
            constraint=models.UniqueConstraint(fields=('social_account', 'day_of_week', 'time'), name='uniq_queue_slot_per_social_account'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['client', 'status'], name='publishing__client__3d63ca_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'scheduled_at'], name='publishing__status_4bc090_idx'),
        ),
        migrations.AddIndex(
            model_name='posttarget',
            index=models.Index(fields=['platform', 'status'], name='publishing__platfor_673e11_idx'),
        ),
        migrations.AddConstraint(
            model_name='posttarget',
            constraint=models.UniqueConstraint(fields=('post', 'social_account'), name='uniq_social_account_target_per_post'),
        ),
        migrations.AddConstraint(
            model_name='posttargetmetricsnapshot',
            constraint=models.UniqueConstraint(fields=('post_target', 'collected_at'), name='uniq_metric_snapshot_per_target_time'),
        ),
    ]
