# Generated by Django 5.2.14 on 2026-05-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttarget',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
