# Generated by Django 5.2.14 on 2026-05-31 12:04

import django.db.models.deletion
import integrations.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('GBP', 'Google Business Profile'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('LINKEDIN', 'LinkedIn'), ('TWITTER', 'X / Twitter')], max_length=16)),
                ('account_name', models.CharField(max_length=180)),
                ('access_token', integrations.fields.EncryptedTextField(blank=True)),
                ('refresh_token', integrations.fields.EncryptedTextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('platform_account_id', models.CharField(blank=True, max_length=255)),
                ('location_id', models.CharField(blank=True, max_length=255)),
                ('page_id', models.CharField(blank=True, max_length=255)),
                ('channel_id', models.CharField(blank=True, max_length=255)),
                ('instagram_business_account_id', models.CharField(blank=True, max_length=255)),
                ('connection_health', models.CharField(choices=[('CONNECTED', 'Connected'), ('EXPIRING', 'Token expiring soon'), ('DISCONNECTED', 'Disconnected'), ('ERROR', 'Error')], default='CONNECTED', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='clients.client')),
            ],
            options={
                'ordering': ['client', 'platform', 'account_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('platform_account_id', ''), _negated=True), fields=('client', 'platform', 'platform_account_id'), name='uniq_remote_social_account_per_client')],
            },
        ),
    ]
