# Generated by Django 5.2.14 on 2026-05-31 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('clients', '0001_initial'),
        ('media', '0001_initial'),
        ('publishing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('post_type', models.CharField(max_length=80)),
                ('brief', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_content_requests', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_requests', to='campaigns.campaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_requests', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_content_requests', to=settings.AUTH_USER_MODEL)),
                ('linked_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_requests', to='publishing.post')),
                ('reference_media', models.ManyToManyField(blank=True, related_name='content_requests', to='media.media')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_request_comments', to=settings.AUTH_USER_MODEL)),
                ('content_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='collaboration.contentrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentRequestStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_request_status_events', to=settings.AUTH_USER_MODEL)),
                ('content_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='collaboration.contentrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentRequestTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('GBP', 'Google Business Profile'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('LINKEDIN', 'LinkedIn'), ('TWITTER', 'X / Twitter')], max_length=16)),
                ('content_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='collaboration.contentrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publishing.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_comment_id', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('remote_created_at', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('reply_body', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_spam_suspected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_comments', to='clients.client')),
                ('post_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_comments', to='publishing.posttarget')),
            ],
            options={
                'ordering': ['-remote_created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contentrequest',
            index=models.Index(fields=['client', 'status'], name='collaborati_client__7f94aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentrequesttarget',
            constraint=models.UniqueConstraint(fields=('content_request', 'platform'), name='uniq_platform_per_content_request'),
        ),
        migrations.AddIndex(
            model_name='unifiedcomment',
            index=models.Index(fields=['client', 'is_read'], name='collaborati_client__882294_idx'),
        ),
        migrations.AddConstraint(
            model_name='unifiedcomment',
            constraint=models.UniqueConstraint(fields=('post_target', 'platform_comment_id'), name='uniq_remote_comment_per_target'),
        ),
    ]
