# Generated by Django 5.2.14 on 2026-06-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('publishing', '0002_posttarget_next_retry_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_attachments', to='media.media')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='publishing.post')),
            ],
            options={
                'ordering': ['position', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('post', 'media'), name='uniq_media_attachment_per_post')],
            },
        ),
    ]
