# Generated by Django 5.2.14 on 2026-05-31 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('POST_PUBLISHED', 'Post published'), ('POST_FAILED', 'Post failed'), ('POST_COMMENT', 'Post comment'), ('ASSET_UPLOADED', 'Asset uploaded'), ('REQUEST_RECEIVED', 'Request received'), ('REQUEST_STATUS_CHANGED', 'Request status changed'), ('REQUEST_COMMENT', 'Request comment'), ('TOKEN_EXPIRING', 'Token expiring'), ('UNIFIED_COMMENT_NEW', 'New unified comment'), ('AI_SUGGESTIONS_READY', 'AI suggestions ready')], max_length=32)),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, max_length=1000)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('POST_PUBLISHED', 'Post published'), ('POST_FAILED', 'Post failed'), ('POST_COMMENT', 'Post comment'), ('ASSET_UPLOADED', 'Asset uploaded'), ('REQUEST_RECEIVED', 'Request received'), ('REQUEST_STATUS_CHANGED', 'Request status changed'), ('REQUEST_COMMENT', 'Request comment'), ('TOKEN_EXPIRING', 'Token expiring'), ('UNIFIED_COMMENT_NEW', 'New unified comment'), ('AI_SUGGESTIONS_READY', 'AI suggestions ready')], max_length=32)),
                ('email_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'type'), name='uniq_notification_preference_per_user_type')],
            },
        ),
    ]
